package org.gdarts.batis;

public class Items {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column items.id
	 * 
	 * @mbggenerated Tue Sep 10 14:29:47 JST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column items.category_id
	 * 
	 * @mbggenerated Tue Sep 10 14:29:47 JST 2013
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column items.item
	 * 
	 * @mbggenerated Tue Sep 10 14:29:47 JST 2013
	 */
	private String item;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column items.id
	 * 
	 * @return the value of items.id
	 * @mbggenerated Tue Sep 10 14:29:47 JST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column items.id
	 * 
	 * @param id
	 *            the value for items.id
	 * @mbggenerated Tue Sep 10 14:29:47 JST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column items.category_id
	 * 
	 * @return the value of items.category_id
	 * @mbggenerated Tue Sep 10 14:29:47 JST 2013
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column items.category_id
	 * 
	 * @param categoryId
	 *            the value for items.category_id
	 * @mbggenerated Tue Sep 10 14:29:47 JST 2013
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column items.item
	 * 
	 * @return the value of items.item
	 * @mbggenerated Tue Sep 10 14:29:47 JST 2013
	 */
	public String getItem() {
		return item;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column items.item
	 * 
	 * @param item
	 *            the value for items.item
	 * @mbggenerated Tue Sep 10 14:29:47 JST 2013
	 */
	public void setItem(String item) {
		this.item = item;
	}
}